title: adnfruzsii's project
description: This is a test site to learn how github pages works
logo: "/docs/images/test.png"
favicon_ico: "/docs/images/test.png"
plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs
url: your_repo_url

aux_links:
  Repository: https://github.com/adnfruzsii/adnfruzsii.github.io
